/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SongSongIdRouteImport } from './routes/song/$songId'
import { Route as ArtistNameRouteImport } from './routes/artist.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SongSongIdRoute = SongSongIdRouteImport.update({
  id: '/song/$songId',
  path: '/song/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistNameRoute = ArtistNameRouteImport.update({
  id: '/artist/$name',
  path: '/artist/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/song/$songId': typeof SongSongIdRoute
  '/artist/$name': typeof ArtistNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/song/$songId': typeof SongSongIdRoute
  '/artist/$name': typeof ArtistNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/song/$songId': typeof SongSongIdRoute
  '/artist/$name': typeof ArtistNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/auth' | '/library' | '/profile' | '/song/$songId' | '/artist/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/auth' | '/library' | '/profile' | '/song/$songId' | '/artist/$name'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/library'
    | '/profile'
    | '/song/$songId'
    | '/artist/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  LibraryRoute: typeof LibraryRoute
  ProfileRoute: typeof ProfileRoute
  SongSongIdRoute: typeof SongSongIdRoute
  ArtistNameRoute: typeof ArtistNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song/$songId': {
      id: '/song/$songId'
      path: '/song/$songId'
      fullPath: '/song/$songId'
      preLoaderRoute: typeof SongSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$name': {
      id: '/artist/$name'
      path: '/artist/$name'
      fullPath: '/artist/$name'
      preLoaderRoute: typeof ArtistNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  LibraryRoute: LibraryRoute,
  ProfileRoute: ProfileRoute,
  SongSongIdRoute: SongSongIdRoute,
  ArtistNameRoute: ArtistNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
